name       : libebur128
version    : 1.2.4
release    : 1
source     :
    - https://github.com/jiixyj/libebur128/archive/v1.2.4.tar.gz : 2ee41a3a5ae3891601ae975d5ec2642b997d276ef647cf5c5b363b6127f7add8
license    : MIT
component  : multimedia.library
summary    : libebur128 is a library that implements the EBU R 128 standard for loudness normalisation.
description: |
    libebur128 is a library that implements the EBU R 128 standard for loudness normalisation.
builddeps  :
    - pkgconfig(sndfile)
setup      : |
    %cmake -DBUILD_STATIC_LIBS=OFF -DENABLE_TESTS=ON
build      : |
    %make
install    : |
    %make_install
